# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/anon/Projects/nf-ebot/scrapers_cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/anon/Projects/nf-ebot/scrapers_cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/anon/Projects/nf-ebot/scrapers_cpp/CMakeFiles /Users/anon/Projects/nf-ebot/scrapers_cpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/anon/Projects/nf-ebot/scrapers_cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named scrapers_cpp

# Build rule for target.
scrapers_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scrapers_cpp
.PHONY : scrapers_cpp

# fast build rule for target.
scrapers_cpp/fast:
	$(MAKE) -f CMakeFiles/scrapers_cpp.dir/build.make CMakeFiles/scrapers_cpp.dir/build
.PHONY : scrapers_cpp/fast

source/libs/geturl.o: source/libs/geturl.cpp.o

.PHONY : source/libs/geturl.o

# target to build an object file
source/libs/geturl.cpp.o:
	$(MAKE) -f CMakeFiles/scrapers_cpp.dir/build.make CMakeFiles/scrapers_cpp.dir/source/libs/geturl.cpp.o
.PHONY : source/libs/geturl.cpp.o

source/libs/geturl.i: source/libs/geturl.cpp.i

.PHONY : source/libs/geturl.i

# target to preprocess a source file
source/libs/geturl.cpp.i:
	$(MAKE) -f CMakeFiles/scrapers_cpp.dir/build.make CMakeFiles/scrapers_cpp.dir/source/libs/geturl.cpp.i
.PHONY : source/libs/geturl.cpp.i

source/libs/geturl.s: source/libs/geturl.cpp.s

.PHONY : source/libs/geturl.s

# target to generate assembly for a file
source/libs/geturl.cpp.s:
	$(MAKE) -f CMakeFiles/scrapers_cpp.dir/build.make CMakeFiles/scrapers_cpp.dir/source/libs/geturl.cpp.s
.PHONY : source/libs/geturl.cpp.s

source/libs/helpers.o: source/libs/helpers.cpp.o

.PHONY : source/libs/helpers.o

# target to build an object file
source/libs/helpers.cpp.o:
	$(MAKE) -f CMakeFiles/scrapers_cpp.dir/build.make CMakeFiles/scrapers_cpp.dir/source/libs/helpers.cpp.o
.PHONY : source/libs/helpers.cpp.o

source/libs/helpers.i: source/libs/helpers.cpp.i

.PHONY : source/libs/helpers.i

# target to preprocess a source file
source/libs/helpers.cpp.i:
	$(MAKE) -f CMakeFiles/scrapers_cpp.dir/build.make CMakeFiles/scrapers_cpp.dir/source/libs/helpers.cpp.i
.PHONY : source/libs/helpers.cpp.i

source/libs/helpers.s: source/libs/helpers.cpp.s

.PHONY : source/libs/helpers.s

# target to generate assembly for a file
source/libs/helpers.cpp.s:
	$(MAKE) -f CMakeFiles/scrapers_cpp.dir/build.make CMakeFiles/scrapers_cpp.dir/source/libs/helpers.cpp.s
.PHONY : source/libs/helpers.cpp.s

source/main.o: source/main.cpp.o

.PHONY : source/main.o

# target to build an object file
source/main.cpp.o:
	$(MAKE) -f CMakeFiles/scrapers_cpp.dir/build.make CMakeFiles/scrapers_cpp.dir/source/main.cpp.o
.PHONY : source/main.cpp.o

source/main.i: source/main.cpp.i

.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) -f CMakeFiles/scrapers_cpp.dir/build.make CMakeFiles/scrapers_cpp.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s

.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) -f CMakeFiles/scrapers_cpp.dir/build.make CMakeFiles/scrapers_cpp.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... scrapers_cpp"
	@echo "... source/libs/geturl.o"
	@echo "... source/libs/geturl.i"
	@echo "... source/libs/geturl.s"
	@echo "... source/libs/helpers.o"
	@echo "... source/libs/helpers.i"
	@echo "... source/libs/helpers.s"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

